"""
Type stubs for pyxpcsviewer XPCS data handling library.
"""

from pathlib import Path
from typing import Any

import numpy as np

class DataExtractor:
    def __init__(self, file_path: str | Path) -> None: ...
    def get_correlation_data(self) -> dict[str, Any]: ...
    def get_experimental_data(self) -> dict[str, Any]: ...
    def get_metadata(self) -> dict[str, Any]: ...

def load_xpcs_data(file_path: str | Path) -> dict[str, Any]: ...
def extract_correlation_function(
    data: dict[str, Any], angle_filter: list[float] | None = ...
) -> np.ndarray: ...
