# file generated by setuptools-scm
# don't change, don't track in version control

__all__ = [
    "__commit_id__",
    "__version__",
    "__version_tuple__",
    "commit_id",
    "version",
    "version_tuple",
]

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    VERSION_TUPLE = tuple[int | str, ...]
    COMMIT_ID = str | None
else:
    VERSION_TUPLE = object
    COMMIT_ID = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE
commit_id: COMMIT_ID
__commit_id__: COMMIT_ID

__version__ = version = "0.7.1.post61+dirty"
__version_tuple__ = version_tuple = (0, 7, 1, "post61", "dirty")

__commit_id__ = commit_id = "g41450dcc3"
